### ISSUE TITLE
Project 5

### ISSUE THREAD

**Issue by karnaksp** [s21NameSpace/CT-05#1]

**Comment by karnaksp** [comment]
Если твоя цель — не только пройти стажировку, но и зарекомендовать себя для дальнейшей работы в компании, тогда тебе важно погрузиться в корпоративную культуру и узнать, какие правила и порядки действуют в компании. А также за время стажировки «стать своим», т. е. встроиться, что означает не только показать результат, но и играть по правилам компании.

Как узнать эти правила и что они включают, будем разбираться в этом проекте. А также затронем тему информационной кибербезопасности. Ты, как сотрудник компании, будешь иметь доступ к данным, и твоя ответственность — защитить компанию от утечек информации и кибератак.

Для начала обратимся к терминологии:

Корпоративная культура — набор норм, традиций и ценностей, которые принимаются членами организации и обеспечивают создание сильной конкурентоспособной команды, объединенной общими целями и мотивациями. А правила, принятые в компании, помогут тебе адаптироваться.

Информационная безопасность — это всесторонняя защищённость информации и поддерживающей её инфраструктуры от любых случайных или злонамеренных воздействий, результатом которых может явиться нанесение ущерба самой информации, ее владельцам или поддерживающей инфраструктуре. Задачи информационной безопасности сводятся к минимизации ущерба, а также к прогнозированию и предотвращению таких воздействий.

Кибербезопасность — совокупность методов и практик защиты от атак злоумышленников для компьютеров, серверов, мобильных устройств, электронных систем, сетей и данных. Кибербезопасность находит применение в самых разных областях, от бизнес-сферы до мобильных технологий. В этом направлении можно выделить несколько основных категорий.

Литература:

[«Новые правила деловой переписки», М. Ильяхов](https://vscode-remote+wsl-002bubuntu-002d22-002e04.vscode-resource.vscode-cdn.net/home/karnaksp/MY_SCHOOL_PROJECTS/Career/CT05-1/materials/%D0%94%D0%B5%D0%BB%D0%BE%D0%B2%D0%B0%D1%8F_%D0%BF%D0%B5%D1%80%D0%B5%D0%BF%D0%B8%D1%81%D0%BA%D0%B0.pdf).
[Большая разница: чем различается корпоративная культура больших корпораций и IT-стартапов](https://www.forbes.ru/karera-i-svoy-biznes/348291-bolshaya-raznica-chem-razlichaetsya-korporativnaya-kultura-bolshih).
[«Правила делового общения. 33 «нельзя» и 33 «можно», Н. Зверева](https://vscode-remote+wsl-002bubuntu-002d22-002e04.vscode-resource.vscode-cdn.net/home/karnaksp/MY_SCHOOL_PROJECTS/Career/CT05-1/materials/%D0%9F%D1%80%D0%B0%D0%B2%D0%B8%D0%BB%D0%B0_%D0%B4%D0%B5%D0%BB%D0%BE%D0%B2%D0%BE%D0%B3%D0%BE_%D0%BE%D0%B1%D1%89%D0%B5%D0%BD%D0%B8%D1%8F.pdf).
[«Манеры для карьеры», О. Шевелева](https://vscode-remote+wsl-002bubuntu-002d22-002e04.vscode-resource.vscode-cdn.net/home/karnaksp/MY_SCHOOL_PROJECTS/Career/CT05-1/materials/%D0%9C%D0%B0%D0%BD%D0%B5%D1%80%D1%8B_%D0%B4%D0%BB%D1%8F_%D0%BA%D0%B0%D1%80%D1%8C%D0%B5%D1%80%D1%8B.pdf).
[Вторая глава книга Дейла Карнеги «Как завоевать друзей»](https://vscode-remote+wsl-002bubuntu-002d22-002e04.vscode-resource.vscode-cdn.net/home/karnaksp/MY_SCHOOL_PROJECTS/Career/CT05-1/materials/%D0%9A%D0%B0%D0%BA_%D0%B7%D0%B0%D0%B2%D0%BE%D0%B5%D0%B2%D0%B0%D1%82%D1%8C_%D0%B4%D1%80%D1%83%D0%B7%D0%B5%D0%B9.pdf).
[Ответственность за утечку персональных данных](https://rt-solar.ru/products/solar_dozor/blog/2795/).
[Что такое кибербезопасность?](https://www.kaspersky.ru/resource-center/definitions/what-is-cyber-security)
[Что такое кибербезопасность?](https://www.sap.com/central-asia-caucasus/products/financial-management/what-is-cybersecurity.html)
Фильм «Стажер», 2015.

**Comment by karnaksp** [comment]
Выполняя этот проект, создай свою ветку репозитория, выполни задачи, скопируй эту форму со своим ником и добавь комментарий ниже. Отметь галочками, что сделано:

Проект **karnaksp**

### До выхода на стажировку/работу

- [x] Ответы на вопросы о компании
- [x] Составь список вопросов о корпоративной культуре, на которые ты не нашел ответы и спросишь в первый рабочий день.

### Первый день

- [x] Напиши письмо коллегам и представь себя. 
- [x] Прикрепи фото. Продумай и прикрепи, какое фото лучше тебя презентует перед командой.

Когда задача будет выполнена, тэгни меня так @karnaksp , чтобы я зафиксировал, что эту задачу можно закрыть и отправиться на ретроспективу.

**Comment by lobanovivanphantom** [comment]
@karnaksp выполнено

**Comment by karnaksp** [comment]
> [@karnaksp](https://github.com/karnaksp) выполнено

а почему не скопировал сообщение и не отметил галочками

**Comment by karnaksp** [comment]
@Hultyrhik тоже жаль, что не отметился, но вижу, что есть твоя ветка, значит можно закрыть задачу?

**Comment by Hultyrhik** [comment]
Да
